on:
  push:
    branches: [ main ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [21.x, 16.x]
        
    steps:
    - name: 🚚 Get latest code
      # uses: actions/checkout@v4
    - uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

      

    # - name: Use Node.js 21
    #   uses: actions/setup-node@v2
    #   with:
    #     node-version: '21'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: yoorankim.com
        username: u909776080
        password: ${{ secrets.FTP_DEPLOY }}
        local-dir: dist/
        server-dir: ./
